#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-String-Similarity
Version  : 1.04
Release  : 9
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/String-Similarity-1.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/String-Similarity-1.04.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libs/libstring-similarity-perl/libstring-similarity-perl_1.04-2.debian.tar.xz
Summary  : ~
Group    : Development/Tools
License  : GPL-2.0
Requires: perl-String-Similarity-lib = %{version}-%{release}
Requires: perl-String-Similarity-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
String::Similarity - calculate the similarity of two strings
SYNOPSIS
use String::Similarity;

%package dev
Summary: dev components for the perl-String-Similarity package.
Group: Development
Requires: perl-String-Similarity-lib = %{version}-%{release}
Provides: perl-String-Similarity-devel = %{version}-%{release}

%description dev
dev components for the perl-String-Similarity package.


%package lib
Summary: lib components for the perl-String-Similarity package.
Group: Libraries
Requires: perl-String-Similarity-license = %{version}-%{release}

%description lib
lib components for the perl-String-Similarity package.


%package license
Summary: license components for the perl-String-Similarity package.
Group: Default

%description license
license components for the perl-String-Similarity package.


%prep
%setup -q -n String-Similarity-1.04
cd ..
%setup -q -T -D -n String-Similarity-1.04 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/String-Similarity-1.04/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-String-Similarity
cp COPYING %{buildroot}/usr/share/package-licenses/perl-String-Similarity/COPYING
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-String-Similarity/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/String/Similarity.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/String::Similarity.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/auto/String/Similarity/Similarity.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-String-Similarity/COPYING
/usr/share/package-licenses/perl-String-Similarity/deblicense_copyright
